import streamlit as st

# Access OpenAI API key from Streamlit secrets
openai_api_key = st.secrets["openai"]["api_key"]

# Access database credentials from Streamlit secrets
db_config = {
    "dbname": st.secrets["postgres"]["dbname"],
    "user": st.secrets["postgres"]["user"],
    "password": st.secrets["postgres"]["password"],
    "host": st.secrets["postgres"]["host"],
    "port": st.secrets["postgres"]["port"]
}
