[openai]
api_key = "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"


[postgres]
dbname = "Employees_db"
user = "fatma-hmz" 
password = "pit_sqlizer_db"
host = "db.supabase.co"
port = 5432
