
[openai]
api_key = "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"

[postgres]
dbname = "test_db"
user = "postgres"
password = "your_super_secret_password"
host = "172.20.0.4"
port = "5432"
